### ISSUE TITLE
PowerShellProTools Licence Key

### ISSUE THREAD

**Issue by GavinEke** [janegilring/PSCommunity#3]
Hi Jan,

Just noticed you have your licence key available in one of your files, not sure if you want to remove that. I saw it here https://github.com/janegilring/PSCommunity/blob/master/Containers/PowerShell%20Universal%20Dashboard/WindowsServerCoreDemoWebsite/dashboard.ps1#L5

This article might help with removing it from any historical commits https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Regards,
-Gavin

**Comment by janegilring** [comment]
Thanks for the heads up, and the pointer to remove it from historical commits
